name: Auto commit

on:
  schedule:
    - cron: '15 4,8,15 * * 0-2'
    - cron: '0 8-20 * * 1-5'
    - cron: '10 3-11 4-20 * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> report.txt
    - name: Commit and Push file
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'nguyenxuanbac88'
        git config --global user.email 'xuanbacatym@gmail.com'
        git pull origin main --rebase # Đồng bộ trước khi push
        git add report.txt
        git commit -am "Automated report"
        git push https://${TOKEN}@github.com/nguyenxuanbac88/AutoCommit.git main
