name: Auto commit

on:
  schedule:
    - cron: '15 4,8,15 * * 0-2'
    - cron: '0 8-20 * * 1-5'
    - cron: '10 3-11 4-20 * *'
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Create sample file with just timestamp
        run: date +%s >> report.txt
      - name: Commit file
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'Automated XB 404'
          git config --global user.email 'NXB123@users.noreply.github.com'
          git add report.txt
          git commit -m "Automated report"
          git push https://${TOKEN}@github.com/nguyenxuanbac88/AutoCommit.git master
